### ISSUE TITLE
error parsing deploy.yml: error converting YAML to JSON: yaml: line 23: did not find expected key

### ISSUE THREAD

**Issue by wanghaowish** [elastic-ai/elastic-gpu-scheduler#20]
操作第4步创建gpu测试deployment时报错，不知道是不是我前面标签没有生效的原因，下面是我的scheduler-policy-config.yaml
`---
apiVersion: kubescheduler.config.k8s.io/v1beta2
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: /etc/kubernetes/scheduler.conf
extenders:
- urlPrefix: "http://<elastic-gpu-scheduler-svc-clusterip>:39999/scheduler"
  filterVerb: filter
  prioritizeVerb: priorities
  bindVerb: bind
  weight: 1
  enableHTTPS: false
  nodeCacheCapable: true
  managedResources:
  - name: elasticgpu.io/gpu-core
  - name: elasticgpu.io/gpu-memory`

**Comment by wanghaowish** [comment]
@xiaoxubeii

**Comment by Cindyi-ctl** [comment]
一般遇到这种问题“error converting YAML to JSON: yaml”，对大的可能性是yaml的格式出错。我经常的解决办法是 对照原有文本的习惯，检查特殊字段前是否要加“-”，以及他们的锁进。

**Comment by xiaoxubeii** [comment]
查下你的 yaml 格式是否对
