### ISSUE TITLE
Mismatching const from elastic-gpu to elastic-gpu-scheduler

### ISSUE THREAD

**Issue by Cindyi-ctl** [elastic-ai/elastic-gpu-scheduler#21]
When I tried to debug the elastic-gpu-scheduler, the controller always missed to grab any elastic pod.
So I found that there was a mismatching const from elastic-gpu to elastic-gpu-scheduler:

In elastic-gpu/apis/elasticgpu/v1alpha1/types.go:
```
const (
	ResourceGPUCore         v1.ResourceName = "elasticgpu.com/gpu-core"
	ResourceGPUMemory       v1.ResourceName = "elasticgpu.com/gpu-memory"
)
```

In elastic-gpu-scheduler/vendor/elasticgpu.io/elastic-gpu/api/elasticgpu.io/v1alpha1/types.go:
```
const (
	ResourceGPUCore         v1.ResourceName = "elasticgpu.io/gpu-core"
	ResourceGPUMemory       v1.ResourceName = "elasticgpu.io/gpu-memory"
)
```

Therefore, if I run `go mod vendor` again, there is a mismatching happened.

**Comment by xiaoxubeii** [comment]
Actually "elasticgpu.io" is the correct prefix. I have fixed out of date reference of elasticgpu which is now elasticgpu.io/elastic-gpu:v0.1-alpha.0
